/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package turo;

import java.util.Scanner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.jar.Attributes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mikaelbjorkqvist1
 */
public class turoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form turoJFrame
     */
    public turoJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nimiTxt = new javax.swing.JTextField();
        hintaTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        kuvausTxt = new javax.swing.JTextArea();
        ryhmaTxt = new javax.swing.JTextField();
        selaaBtn = new javax.swing.JButton();
        muokkaaBtn = new javax.swing.JButton();
        poistaBtn = new javax.swing.JButton();
        lisaaBtn = new javax.swing.JButton();
        tallennaBtn = new javax.swing.JButton();
        paivitaBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        turoTbl = new javax.swing.JTable();
        UpdateTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TURO");

        jLabel1.setText("Tuotteet:");

        jLabel2.setText("Nimi:");

        jLabel3.setText("Hinta:");

        jLabel4.setText("Kuvaus:");

        jLabel5.setText("Tuoteryhmä:");

        kuvausTxt.setColumns(20);
        kuvausTxt.setRows(5);
        jScrollPane1.setViewportView(kuvausTxt);

        selaaBtn.setText("Selaa");
        selaaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selaaBtnActionPerformed(evt);
            }
        });

        muokkaaBtn.setText("Muokkaa");
        muokkaaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muokkaaBtnActionPerformed(evt);
            }
        });

        poistaBtn.setText("Poista");
        poistaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poistaBtnActionPerformed(evt);
            }
        });

        lisaaBtn.setText("Tyhjennä kentät");
        lisaaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaBtnActionPerformed(evt);
            }
        });

        tallennaBtn.setText("Tallenna uusi");
        tallennaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallennaBtnActionPerformed(evt);
            }
        });

        paivitaBtn.setText("Päivitä");
        paivitaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paivitaBtnActionPerformed(evt);
            }
        });

        turoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tuotetunnus", "Nimi", "Hinta", "Kuvaus", "Tuoteryhmä"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(turoTbl);
        if (turoTbl.getColumnModel().getColumnCount() > 0) {
            turoTbl.getColumnModel().getColumn(0).setResizable(false);
            turoTbl.getColumnModel().getColumn(0).setPreferredWidth(40);
            turoTbl.getColumnModel().getColumn(1).setResizable(false);
            turoTbl.getColumnModel().getColumn(1).setPreferredWidth(100);
            turoTbl.getColumnModel().getColumn(2).setResizable(false);
            turoTbl.getColumnModel().getColumn(2).setPreferredWidth(40);
            turoTbl.getColumnModel().getColumn(3).setResizable(false);
            turoTbl.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(selaaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(muokkaaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(poistaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lisaaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tallennaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paivitaBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hintaTxt)
                            .addComponent(nimiTxt)
                            .addComponent(ryhmaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lisaaBtn, muokkaaBtn, paivitaBtn, poistaBtn, selaaBtn, tallennaBtn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nimiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(hintaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ryhmaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selaaBtn)
                    .addComponent(muokkaaBtn)
                    .addComponent(poistaBtn)
                    .addComponent(lisaaBtn)
                    .addComponent(tallennaBtn)
                    .addComponent(paivitaBtn))
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lisaaBtn, muokkaaBtn, paivitaBtn, poistaBtn, selaaBtn, tallennaBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selaaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selaaBtnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement statement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;
        DefaultTableModel model = (DefaultTableModel) turoTbl.getModel();
        while (turoTbl.getRowCount() > 0) {
            model.removeRow(0);
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/turo", "root", "");

            statement = connect.createStatement();
            String sql;
            sql = "SELECT Tuotetunnus, Nimi, Hinta, Kuvaus, Tuoteryhmä FROM kauppa";
            ResultSet rs = statement.executeQuery(sql);
            while (rs.next()) {
                
                String product = rs.getString("Tuotetunnus");
                String name = rs.getString("Nimi");
                String price = rs.getString("Hinta");
                String info = rs.getString("Kuvaus");
                String group = rs.getString("Tuoteryhmä");
                
                model.addRow(new Object [] {"" + product, name, price, info, group});
            }
            
            rs.close();
            statement.close();
            connect.close();

        } catch (SQLException se) {
            se.printStackTrace();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_selaaBtnActionPerformed

    private void muokkaaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muokkaaBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) turoTbl.getModel();
        int row = turoTbl.getSelectedRow();
        if (row >= 0) {
            
            nimiTxt.setText((String) model.getValueAt(row, 1));
            hintaTxt.setText((String) model.getValueAt(row, 2));
            kuvausTxt.setText((String) model.getValueAt(row, 3));
            ryhmaTxt.setText((String) model.getValueAt (row, 4));
                    
        }
    }//GEN-LAST:event_muokkaaBtnActionPerformed

    private void poistaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poistaBtnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement statement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/turo", "root", "");

            statement = connect.createStatement();
            String sql;
            sql = "DELETE FROM kauppa WHERE Tuotetunnus=?;";
            PreparedStatement preparedStmt = connect.prepareStatement(sql);
            DefaultTableModel model = (DefaultTableModel) turoTbl.getModel();
            int row = turoTbl.getSelectedRow();
            if (row >= 0) {
                preparedStmt.setString(1, (String) model.getValueAt(row, 0));
                preparedStmt.execute();
                statement.close();
                connect.close();
            }

        } catch (SQLException se) {
            se.printStackTrace();

        } catch (Exception e) {
            e.printStackTrace();
        }
        UpdateTxt.setText("Tieto poistettu");
    }//GEN-LAST:event_poistaBtnActionPerformed

    private void lisaaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaBtnActionPerformed
        // TODO add your handling code here:
        nimiTxt.setText("");
        hintaTxt.setText("");
        kuvausTxt.setText("");
        ryhmaTxt.setText("");
    }//GEN-LAST:event_lisaaBtnActionPerformed

    private void tallennaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallennaBtnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement statement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/turo", "root", "");

            statement = connect.createStatement();
            String sql;
            sql = "INSERT INTO kauppa (Nimi, Hinta, Kuvaus, Tuoteryhmä) VALUES (?, ?, ?, ?);";
            PreparedStatement preparedStmt = connect.prepareStatement(sql);
            preparedStmt.setString(1, nimiTxt.getText());
            preparedStmt.setString(2, hintaTxt.getText());
            preparedStmt.setString(3, kuvausTxt.getText());
            preparedStmt.setString(4, ryhmaTxt.getText());
            preparedStmt.execute();
            statement.close();
            connect.close();

        } catch (SQLException se) {
            se.printStackTrace();

        } catch (Exception se) {
            se.printStackTrace();
        }
        UpdateTxt.setText("Tieto lisätty");
    }//GEN-LAST:event_tallennaBtnActionPerformed

    private void paivitaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paivitaBtnActionPerformed
        // TODO add your handling code here:
        Connection connect = null;
        Statement statement = null;
        PreparedStatement preparedStatement = null;
        ResultSet resultSet = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            connect = DriverManager.getConnection("jdbc:mysql://localhost/turo", "root", "");

            DefaultTableModel model = (DefaultTableModel) turoTbl.getModel();
            int row = turoTbl.getSelectedRow();
            
            statement = connect.createStatement();
            String sql;
            sql = "UPDATE kauppa SET Nimi=?, Hinta=?, Kuvaus=?, Tuoteryhmä=? WHERE Tuotetunnus=?";
            PreparedStatement preparedStmt = connect.prepareStatement(sql);
            preparedStmt.setString(1, nimiTxt.getText());
            preparedStmt.setString(2, hintaTxt.getText());
            preparedStmt.setString(3, kuvausTxt.getText());
            preparedStmt.setString(4, ryhmaTxt.getText());
            preparedStmt.setString(5, (String)turoTbl.getValueAt(row, 0));
            
            
            preparedStmt.execute();
            statement.close();
            connect.close();

        } catch (SQLException se) {
            se.printStackTrace();

        } catch (Exception e) {
            e.printStackTrace();
        }
        UpdateTxt.setText("Tieto päivitetty");
    }//GEN-LAST:event_paivitaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(turoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(turoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(turoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(turoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new turoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UpdateTxt;
    private javax.swing.JTextField hintaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea kuvausTxt;
    private javax.swing.JButton lisaaBtn;
    private javax.swing.JButton muokkaaBtn;
    private javax.swing.JTextField nimiTxt;
    private javax.swing.JButton paivitaBtn;
    private javax.swing.JButton poistaBtn;
    private javax.swing.JTextField ryhmaTxt;
    private javax.swing.JButton selaaBtn;
    private javax.swing.JButton tallennaBtn;
    private javax.swing.JTable turoTbl;
    // End of variables declaration//GEN-END:variables
}
